version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=music_db
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - music-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_LOGIN} -d music_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/music_db
      - SPRING_DATASOURCE_USERNAME=${DB_LOGIN}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - '8081:8081'
    networks:
      - music-network

networks:
  music-network:
    driver: bridge

volumes:
  postgres-data:
